services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: host
    restart: always

  logic:
    build:
      context: .
      dockerfile: DockerFileLogic
    container_name: logic
    depends_on:
      - redis
    network_mode: host
    environment:
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
    volumes:
      - "./Backend-Simulation:/app"
    restart: always

  server:
    build:
      context: .
      dockerfile: DockerFileServer
    container_name: server
    depends_on:
      - redis
    network_mode: host
    environment:
      API_HOST: "localhost"
      API_PORT: 8000
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
      DATABASE: "database.db"
    volumes:
      - "./api_server/app:/app"
    restart: always

  input:
    build:
      context: .
      dockerfile: DockerFileInput
    container_name: input
    depends_on:
      - server
    ports:
      - "7000:80"
    volumes:
      - "./input-board/build:/usr/share/nginx/html"
    restart: always

  simulation:
    build:
      context: .
      dockerfile: DockerFileSimulation
    container_name: simulation
    depends_on:
      - server
    ports:
      - "5000:80"
    volumes:
      - "./FrontEndSimulation/dist:/usr/share/nginx/html"
    restart: always
