services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  logic:
    build:
      context: .
      dockerfile: DockerFileLogic
    container_name: logic
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    restart: always

  server:
    build:
      context: .
      dockerfile: DockerFileServer
    container_name: server
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "8000"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      DATABASE: "database.db"
    volumes:
      - "./api_server/app:/app"
    restart: always

  input:
    build:
      context: .
      dockerfile: DockerFileInput
    container_name: input
    depends_on:
      - server
    ports:
      - "7000:80"
    volumes:
      - "./input-board/build:/usr/share/nginx/html"
    restart: always

  simulation:
    build:
      context: .
      dockerfile: DockerFileSimulation
    container_name: simulation
    depends_on:
      - server
    ports:
      - "5000:80"
    volumes:
      - "./FrontEndSimulation/dist:/usr/share/nginx/html"
    restart: always
